// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {engine} from '../models';
import {desktop} from '../models';

export function ExportLastReport(arg1:string):Promise<void>;

export function StartRun(arg1:engine.TestPlan,arg2:desktop.DesktopRunOptions):Promise<engine.RunResult>;

export function StopRun():Promise<void>;

export function ValidatePlan(arg1:engine.TestPlan,arg2:desktop.DesktopRunOptions):Promise<string>;
