// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExportLastReport(arg1) {
  return window['go']['desktop']['App']['ExportLastReport'](arg1);
}

export function GetRunSnapshot() {
  return window['go']['desktop']['App']['GetRunSnapshot']();
}

export function StartRun(arg1, arg2) {
  return window['go']['desktop']['App']['StartRun'](arg1, arg2);
}

export function StopRun() {
  return window['go']['desktop']['App']['StopRun']();
}

export function ValidatePlan(arg1, arg2) {
  return window['go']['desktop']['App']['ValidatePlan'](arg1, arg2);
}
